var _od_path="scripts/pxalign.js";window.onpopstate=function(a){window.location.reload(!0)};
if((window.__hv_||window.document.__hv_)&&parent===window){var CreateFrame=function(a){var b=window.document.createElement("iframe");b.src="about:blank";b.style.cssText="position:fixed;left:0px;top:0px;padding:0px;width:100%;height:100%;border:none;outline:none;overflow:hidden;"+(a&&"display:none;"||"");window.document.documentElement.insertBefore(b,window.document.documentElement.firstChild);return b};(function(){var a=new XMLHttpRequest;a.open("GET",window.location.href,!1);a.send();a=a.responseText;
var b=CreateFrame(!1);b.contentDocument.open("text/html","replace");b.contentDocument.write(a.replace("<head>",'<head><base target="_parent">').replace(/<\/body>(?!.+<\/body>)/,'<script src="'+_od_path+'">\x3c/script></body>'));b.contentDocument.close()})();(function(){var a=document.getElementsByTagName("script");a&&(a=a[a.length-1])&&(a.gtfo=a.removeNode||a.remove,a.gtfo());var b=window.document.getElementsByTagName("iframe")[0];var d=CreateFrame(!1);window.addEventListener("message",function(a){switch(a.data[0]){case "HDNAV":if(window.__http_nav_cache&&
window.__http_nav_cache[a.data[1]])var c=window.__http_nav_cache[a.data[1]];else c=new XMLHttpRequest,c.open("GET",a.data[1],!1),c.send(),c=c.responseText.replace("<head>",'<head><base target="_parent">').replace(/<\/body>(?!.+<\/body>)/,'<script src="'+_od_path+'">\x3c/script></body>');window.prev_page_url=window.location.href;history.pushState(null,null,a.data[1]);b.gtfo=b.removeNode||b.remove;d.contentDocument.open("text/html","replace");d.contentWindow.prev_page_url=window.prev_page_url;d.contentDocument.write(c);
d.contentDocument.close();window.__http_nav_cache={};b.gtfo();b=d;d=CreateFrame(!1)}},b.contentWindow)})()}
window.__hv_||window.document.__hv_||parent===window||!parent.window.document.__hv_&&!parent.window.__hv_||function(){if(window.__bodyload)window.__bodyload=!0;else{(function(){parent.__http_nav_cache||(parent.__http_nav_cache={});for(var a=parent.document.location.hostname,b=document.getElementsByTagName("a"),c,e=(c=b.length)-1;c;e=--c-1){var f;if(b[e]&&(f=b[e].href)){var h=f.indexOf(a)+1;h&&9>=h&&f&&!b[e].hash&&"#"!=b[e].href.charAt(b[e].href.length-1)&&(e=new XMLHttpRequest,e._url=f,e.open("GET",
e._url),e.onreadystatechange=function(){this&&4==this.readyState&&200==this.status&&parent&&parent.__http_nav_cache&&!parent.__http_nav_cache[this._url]&&(parent.__http_nav_cache[this._url]=this.responseText.replace("<head>",'<head><base target="_parent">').replace(/<\/body>(?!.+<\/body>)/,'<script src="'+_od_path+'">\x3c/script></body>'))},e.send())}}})();var a=document.location.hostname,b=null;(function(){for(var d=document.getElementsByTagName("a"),g,c=(g=d.length)-1;g;c=--g-1)if(d[c]){var e;if((e=
d[c].href)&&!d[c].hash&&"#"!=d[c].href.charAt(d[c].href.length-1)){var f=e.indexOf(a)+1;f&&9>=f&&e&&("odcache"in d[c].attributes&&parent.postMessage(["HDGET",d[c].href],"*"),"odskip"in d[c].attributes?d[c].setAttribute("no-od",""):(d[c].setAttribute("od",""),d[c].onclick=function(b){b.preventDefault()},d[c].onmousedown=function(a){0===a.button&&(b=a.currentTarget,parent.postMessage(["HDNAV",a.currentTarget.href],"*"))},d[c].onmouseleave=function(a){b===a.currentTarget&&(b=null)},d[c].onmouseup=function(a){0===
a.button&&b===a.currentTarget&&(b=null)}))}}})()}}();
if(!(window.__hv_||window.document.__hv_||parent.window.__hv_||parent.window.document.__hv_)&&parent===window){for(window.__hv_=window.document.__hv_=!0;document.documentElement.firstChild;)document.documentElement.removeChild(document.documentElement.firstChild);document.write('<meta name="viewport" content="width=device-width, initial-scale=1"></head><body><script>window.document.close();while(document.documentElement.firstChild)document.documentElement.removeChild(document.documentElement.firstChild);(function(){var q=document.createElement("script");q.type = "text/javascript";q.src  = "'+_od_path+
'";document.documentElement.appendChild(q);})();\x3c/script></body>');window.document.close();var mobile_meta=document.createElement("meta");mobile_meta.name="viewport";mobile_meta.content="width=device-width, initial-scale=1";window.document.documentElement.appendChild(mobile_meta)}else if(parent!==window){var tmps=document.getElementsByTagName("script");if(tmps){var tmp=tmps[tmps.length-1];tmp&&(tmp.gtfo=tmp.removeNode||tmp.remove,tmp.gtfo())}};